### ISSUE TITLE
Support older frameworks

### ISSUE THREAD

**Issue by NN---** [StephenCleary/Cancellation#2]
Using [Theraot.Core](https://www.nuget.org/packages/Theraot.Core/) it is possible to support old .NET Framework versions.
I can submit PRs for these changes.
Will this be accepted ?

**Comment by StephenCleary** [comment]
The library currently supports:

- .NET Core 1.0
- .NET Framework 4.5
- Mono 4.6
- Xamarin.iOS 10.0
- Xamarin.Mac 3.0
- Xamarin.Android 7.0
- Universal Windows Platform 10.0
- Unity 2018.1
- Windows Apps 8.0
- Windows Phone 8.1
- Windows Phone Silverlight 8.0

What other platforms/versions do you need?

**Comment by NN---** [comment]
Using Theraot it can support even 
NET 2.0.

**Comment by StephenCleary** [comment]
My question is: do you *need* it to support .NET 2.0?

I'm not planning to support something Microsoft doesn't even support (and in this case, [hasn't supported for almost a decade](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework)).

**Comment by NN---** [comment]
Unfortunately there are still usages of older .NET versions.
Anyway, if you are not interested , then I will not submit any PRs.

**Comment by StephenCleary** [comment]
I'm not interested at this time, but thanks for the link! If someone does need .NET 2.0 support in the future, I'll know where to look. :)

**Comment by NN---** [comment]
It has support for everything .NET FW 2.0,3.5,4.0 .NET Standard 1.0 and above.
I think 3.5 and 4.0 can be useful.
